apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devportal-charts.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devportal
  template:
    metadata:
      labels:
        app: devportal
    spec:
      {{- if .Values.dockerRegistrySecretName }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecretName }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "devportal-charts.fullname" . }}-credentials
            - configMapRef:
                name: {{ include "devportal-charts.fullname" . }}-app-env
          env:
            - name: NODE_ENV
              value: {{ .Values.nodeEnv | default "development" }}      