apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devportal-charts.fullname" . }}-app-env
  namespace:  {{ .Values.namespace}}
data:
  APP_CONFIG_app_baseUrl: {{ .Values.appConfig.app.baseUrl | quote | quote }}
  APP_CONFIG_backend_baseUrl: {{ .Values.appConfig.backend.baseUrl | quote | quote }}