apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devportal-charts.fullname" . }}-credentials
type: Opaque
data:
  OKTA_CLIENT_ID: {{ .Values.auth.okta.clientId | b64enc}}
  OKTA_AUDIENCE: {{ .Values.auth.okta.audience | b64enc }}
  OKTA_CLIENT_SECRET: {{ .Values.auth.okta.clientSecret | b64enc }}
  GITHUB_TOKEN_SECRET: {{ .Values.githubToken | b64enc }}
  GITHUB_SPECHOUSE_URL: {{ .Values.githubSpecHouseURL | b64enc }}
