# command to apply all kubernetes artifacts.
# kubectl apply -f k8s/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: youroktetonamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: yourbackstageimage
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: backstage-secrets