apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: youroktetonamespace
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: 7007